[package]
name = "chip8_hw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
chip8_decode = { path = "../chip8_decode" }
rand = "~0.8"